name: Publish to npm

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.com'

            - name: 'Install dependencies'
              run: npm ci

            - name: 'Test'
              run: npm run test

            - name: 'Build'
              run: npm run build

            - name: 'Publish'
              run: |
                  if [[ "${{ github.event.release.tag_name }}" == *"rc"* ]]; then
                    npm publish --access public --provenance --tag rc
                  elif [[ "${{ github.event.release.tag_name }}" == *"beta"* ]]; then
                    npm publish --access public --provenance --tag beta
                  else
                    npm publish --access public --provenance --tag latest
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
