name: Test
on:
    pull_request_target:
        branches: ['*']
    push:
        branches: ['*']

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            # Required to checkout the code
            contents: write
            checks: write
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN  }}
