name: Test and Coverage
on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']
    pull_request_target:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ArtiomTr/jest-coverage-report-action@v2
