name: Test and Coverage
on:
    pull_request_target:
        branches: ['*']
    push:
        branches: ['*']

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.COV_TOKEN }}
